name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2022.1.8

      - name: Install requirements
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint

      - name: Codestyle
        run: pipenv run codestyle

